from sys import argv
from os import makedirs, path, remove, rename
from datetime import date
from socket import gethostname
from zipfile import ZipFile
from shutil import rmtree, move, make_archive
import re

def usage():
    print("Usage: python create_flashable_firmware.py ROM_FILE")
    exit()


def create_updater():
    today = str(date.today())
    host = str(gethostname())
    print("Generating updater-script..")
    with open("tmp/META-INF/com/google/android/updater-script", 'r') as i, \
            open("out/updater-script", "w") as o:
        o.writelines("show_progress(0.200000, 10);" + '\n' + '\n')
        o.writelines("# Generated by Xiaomi Flashable Firmware Creator" + '\n'
                     + "# " + today + " - " + host + '\n' + '\n')
        o.writelines(line for line in i if "getprop" in line or "Target" in line or "firmware" in line)
        o.writelines('\n' + "show_progress(0.100000, 2);" + '\n' + "set_progress(1.000000);" + '\n')
    with open("out/updater-script", 'r') as i, \
            open("out/META-INF/com/google/android/updater-script", "w") as o:
        correct = i.read().replace('/firmware/image/sec.dat', '/dev/block/bootdevice/by-name/sec')\
            .replace('/firmware/image/splash.img', '/dev/block/bootdevice/by-name/splash')
        o.write(correct)
    remove('out/updater-script')


def main():
    rom = argv[1]
    makedirs("tmp", exist_ok=True)
    tmp_dir = "tmp"
    archive = ZipFile(rom)
    print("Unzipping MIUI..")
    for file in archive.namelist():
        if file.startswith('firmware-update') or file.startswith('META-INF'):
            archive.extract(file, tmp_dir)
        else:
            print("Neither firmware-update nor META-INF found!")
            rmtree(tmp_dir)
            exit(1)
    if not path.exists(tmp_dir + '/firmware-update') \
            or path.exists(tmp_dir + 'META-INF/com/google/android/update-binary') \
            or path.exists(tmp_dir + 'META-INF/com/google/android/updater-script'):
        print("This zip doesn't contain firmware directory.")
        rmtree(tmp_dir)
        exit(1)
    makedirs("out", exist_ok=True)
    move(tmp_dir + '/firmware-update/', 'out/firmware-update/')
    makedirs("out/META-INF/com/google/android", exist_ok=True)
    move(tmp_dir + '/META-INF/com/google/android/update-binary', 'out/META-INF/com/google/android/')
    create_updater()
    print("Creating firmware zip from " + rom)
    make_archive('firmware', 'zip', 'out/')
    if path.exists('firmware.zip'):
        rename('firmware.zip', 'fw_' + rom)
        print("All done!")
        rmtree(tmp_dir)
        rmtree('out')
    else:
        print("Failed!" + '\n' + "Check out folder!")


if len(argv) < 2 or len(argv) > 2:
    usage()
else:
    main()
